Oleg homework Lesson 5
AlexJavaGuru/java_1_tuesday_2021 pull request #12
Opened 2021-08-26 09:11 UTC by Olegs-github

2021-08-29 20:19 UTC, AlexJavaGuru requested changes

2021-08-29 20:19 UTC, AlexJavaGuru commented on src/main/java/student_oleg_kozlov/lesson_5/level_4/Task_29.java
> +        int counter = 0;
Не много не понимаю, зачем вам переменная counter?

2021-08-29 20:19 UTC, AlexJavaGuru commented on src/main/java/student_oleg_kozlov/lesson_5/level_4/Task_30.java
> +        int counter = 0;
И тут?

2021-08-30 07:33 UTC, Olegs-github commented on src/main/java/student_oleg_kozlov/lesson_5/level_4/Task_29.java
> +        int counter = 0;
Была идея использовать его для вывода фразы "Even numbers are: " при первом найденном числе для вывода, а затем выводить числа просто через запятую... Может лучше было использовать для этого boolean флажок или вообще использовать другой алгоритм...?

2021-08-30 07:34 UTC, Olegs-github commented on src/main/java/student_oleg_kozlov/lesson_5/level_4/Task_30.java
> +        int counter = 0;
Аналогично с верхним вариантом (src/main/java/student_oleg_kozlov/lesson_5/level_4/Task_29.java)

2021-08-30 18:59 UTC, AlexJavaGuru approved these changes

2021-08-30 18:59 UTC, AlexJavaGuru commented on src/main/java/student_oleg_kozlov/lesson_5/level_4/Task_29.java
> +        int counter = 0;
Ну можно и так оставить. Тут больше такие условности. Как бы вы хотели чтобы код реагировал на то, что там нет четных чисел? Можно было бы просто показывать эту строку перед циклом 1 один раз. Но я понимаю идею.

2021-08-30 18:59 UTC, merged