Ruslan: Lesson_5 Task 1 - 43;
AlexJavaGuru/java_1_tuesday_2021 pull request #13
Opened 2021-08-26 11:16 UTC by RuslanPankratov

2021-08-29 20:31 UTC, AlexJavaGuru requested changes

2021-08-29 20:31 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_5/level_2/ArrayOfNumbersMath.java
> +        int numberOne = (int) (Math.random() * 100 + 10);
Наверное лучше просто в цикле заполнить массив случайными числами, без промежуточных переменных.

2021-08-29 20:31 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_5/level_2/ArrayOfNumbersMath.java
> +        number[0] = number[0] + 2;
Попробуйте использовать для этого цикл

2021-08-29 20:31 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_5/level_2/ArrayOfNumbersRandom.java
> +        int one = (int) (Math.random() * 7 + 10);
Сделайте заполнение в цикле

2021-08-29 20:31 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_5/level_2/ArrayOfNumbersRandomMean.java
> +        int result = (number[0] + number[1] + number[2]) / 3;
А в точности не потеряем при такой операции?

2021-08-29 20:31 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_5/level_4/ArrayOfNumberMax.java
> +        int max = 0;
А если у меня будет массив отрицательных чисел? И еще, лучше создавать такие переменные рядом с тем местом, к которому они относятся в данном случае.

2021-08-29 20:31 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_5/level_4/ArrayOfNumberMin.java
> +        int min = 100;
А почему 100?

2021-08-29 20:31 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_5/level_6/ArrayUtil.java
> +public class ArrayUtil {
Вы могли просто дополнить старый ArrayUtil новыми методами

2021-08-29 20:31 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_5/level_6/ArrayUtilTest.java
> +class ArrayUtilTest {
Это не похоже на тесты. Посмотрите, как мы писали тестовые сценарии на лекции.

2021-08-30 14:22 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_5/level_2/ArrayOfNumbersMath.java
> +        int numberOne = (int) (Math.random() * 100 + 10);
Done

2021-08-30 14:22 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_5/level_2/ArrayOfNumbersMath.java
> +        number[0] = number[0] + 2;
Done

2021-08-30 14:22 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_5/level_2/ArrayOfNumbersRandom.java
> +        int one = (int) (Math.random() * 7 + 10);
Done

2021-08-30 14:22 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_5/level_2/ArrayOfNumbersRandomMean.java
> +        int result = (number[0] + number[1] + number[2]) / 3;
Done

2021-08-30 14:22 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_5/level_4/ArrayOfNumberMax.java
> +        int max = 0;
Done

2021-08-30 14:22 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_5/level_4/ArrayOfNumberMin.java
> +        int min = 100;
Done

2021-08-30 14:22 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_5/level_6/ArrayUtil.java
> +public class ArrayUtil {
Done

2021-08-30 14:22 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_5/level_6/ArrayUtilTest.java
> +class ArrayUtilTest {
Done

2021-08-30 20:53 UTC, AlexJavaGuru requested changes

2021-08-30 20:53 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_5/level_5/ArrayUtil.java
> +        int min = 1000;
а почему 1000? Я думаю, что надо предположить, что самое маленькое число у нас это первое число в массиве (или последнее, в зависимости от направления прохода по массиву.

2021-08-30 20:53 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_5/level_5/ArrayUtil.java
> +        int max = 0;
А почему 0?

2021-08-31 11:02 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_5/level_5/ArrayUtil.java
> +        int max = 0;
Done

2021-08-31 11:02 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_5/level_5/ArrayUtil.java
> +        int min = 1000;
Done

2021-08-31 11:31 UTC, AlexJavaGuru submitted a review, later dismissed

2021-08-31 11:49 UTC, AlexJavaGuru approved these changes

2021-08-31 11:49 UTC, merged