Lesson 4 homework
AlexJavaGuru/java_1_tuesday_2021 pull request #14
Opened 2021-08-26 19:22 UTC by NovemberCharlie1

Olga: Lesson 4 homework

2021-08-30 21:08 UTC, AlexJavaGuru requested changes
Нужно поправить.

2021-08-30 21:08 UTC, AlexJavaGuru commented on src/main/java/student_olga_urek/Lesson_3/level_7/Computer.java
> +class ComputerDemo {
Лучше пока не писать вложенные классы.

2021-08-30 21:08 UTC, AlexJavaGuru commented on src/main/java/student_olga_urek/Lesson_4/level_7/FizzBuzzTest.java
> +    } //тест проваливается, и я не понимаю, почему. Код работает.
Потому, что при создании переменной типа "" + number, джава не будет использовать уже созданную строку в памяти для оптимизации. В место этого, у вас в памяти будет два объекта со значением 8. Так как знак == это проверка равенства ссылок (мы об этом еще будем говорить), то ссылки у них разные (т.к. два разных объекта).
Чтобы решить проблему, надо использовать метод .equals - Вот так должно быть:
realResult.equals(expectedResult)

2021-09-03 18:13 UTC, NovemberCharlie1 commented on src/main/java/student_olga_urek/Lesson_3/level_5/Doggo.java
> +class Doggo {
Неужели кто-то при списывании названия классов не меняет? :О Были проблемы с бранчами, но, вроде бы, разобрались.

2021-09-03 18:16 UTC, NovemberCharlie1 commented on src/main/java/student_olga_urek/Lesson_3/level_5/Doggo.java
> +    public Doggo(String doggoName, int doggoAge, String doggoColor) {
fixed

2021-09-03 18:17 UTC, NovemberCharlie1 commented on src/main/java/student_olga_urek/Lesson_3/level_5/Doggo.java
> +        this.name = doggoName;
fixed

2021-09-03 18:18 UTC, NovemberCharlie1 commented on src/main/java/student_olga_urek/Lesson_3/level_5/Doggo.java
> +    public void voice () {System.out.println(this.name + " " + this.name + " " + this.name + "!");}
fixed

2021-09-03 18:20 UTC, NovemberCharlie1 commented on src/main/java/student_olga_urek/Lesson_3/level_7/Automobile.java
> +    public void tankStatus () {System.out.println("Your car has " + petrol + " liters of petrol in the tank!");}
fixed.

2021-09-03 18:20 UTC, NovemberCharlie1 commented on src/main/java/student_olga_urek/Lesson_3/level_5/Doggo.java
> +    public int happyBirthday () {
fixed.

2021-09-03 18:21 UTC, NovemberCharlie1 commented on src/main/java/student_olga_urek/Lesson_3/level_7/Cat.java
> +        this.weight = weight + 0.25;
fixed.

2021-09-03 18:21 UTC, NovemberCharlie1 commented on src/main/java/student_olga_urek/Lesson_3/level_7/Circle.java
> +    void calculateArea () {
ok.

2021-09-03 18:22 UTC, NovemberCharlie1 commented on src/main/java/student_olga_urek/Lesson_3/level_7/Computer.java
> +class ComputerDemo {
fixed

2021-09-03 18:25 UTC, NovemberCharlie1 commented on src/main/java/student_olga_urek/Lesson_4/level_7/FizzBuzzTest.java
> +    } //тест проваливается, и я не понимаю, почему. Код работает.
fixed.

2021-09-03 19:06 UTC, AlexJavaGuru approved these changes

2021-09-03 19:06 UTC, merged