Em lesson 4
AlexJavaGuru/java_1_tuesday_2021 pull request #15
Opened 2021-08-26 20:48 UTC by Einarok

2021-08-30 21:14 UTC, AlexJavaGuru requested changes

2021-08-30 21:14 UTC, AlexJavaGuru commented on src/main/java/student_einars_marhilevics/lesson_4/level_4/Calculator.java
> +    int maxOfThreeNumbers(int firstNumber, int secondNumber, int thirdNumber) {
Как можно оптимизировать алгоритм? Учитывая, что тут у нас есть два сценария, когда мы возвращаем то или иное число.

2021-08-30 21:14 UTC, AlexJavaGuru commented on src/main/java/student_einars_marhilevics/lesson_4/level_6/StockTest.java
> +    void updatePriceTest() {
Это всё надо разбить на разные тестовые сценарии.

2021-08-30 21:14 UTC, AlexJavaGuru commented on src/main/java/student_einars_marhilevics/lesson_4/level_7/FizzBuzzTest.java
> +        if (realResult.equals(expectedResult)) {
+ за .equals

2021-08-31 06:29 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_4/level_7/FizzBuzzTest.java
> +        if (realResult.equals(expectedResult)) {
ne sovsem ponjal etot komentarij...

2021-08-31 07:41 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_4/level_4/Calculator.java
> +    int maxOfThreeNumbers(int firstNumber, int secondNumber, int thirdNumber) {
fixed

2021-08-31 07:41 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_4/level_6/StockTest.java
> +    void updatePriceTest() {
fixed

2021-09-01 18:43 UTC, AlexJavaGuru approved these changes

2021-09-01 18:43 UTC, merged