Em lesson 5
AlexJavaGuru/java_1_tuesday_2021 pull request #18
Opened 2021-08-30 20:10 UTC by Einarok

Lesson 5

2021-09-02 21:03 UTC, AlexJavaGuru requested changes
Кое что поправить надо

2021-09-02 21:06 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/leson_2/level_7/ProductDemo.java
> +/*package student_ruslan_pankratov.leson_2.level_7;
Я всё исправил.

2021-09-02 21:07 UTC, AlexJavaGuru requested changes
Надо поправить

2021-09-03 13:03 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_5/level_5/ArrayUtil.java
> +        int smallNum = Integer.MAX_VALUE;
Integer.MAX_VALUE raven 2147483647, eto znachit, shto ljuboje chislo masiva budet menshe chem Integer.MAX_VALUE, takzhe i s otricateljnimi chislami

2021-09-03 13:16 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_5/level_2/TASK_13.java
> +        for (int i = 0; i < numbers.length; i++) {
fixed

2021-09-03 13:16 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_5/level_5/ArrayUtil.java
> +        for (int i = 0; i < array.length; i++) {
fixed

2021-09-03 13:16 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_5/level_5/ArrayUtil.java
> +        int bigNum = 0;
fixed

2021-09-03 13:16 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_5/level_5/ArrayUtilTest.java
> +    public void shouldFindMaxNumber() {
fixed

2021-09-05 19:48 UTC, AlexJavaGuru approved these changes

2021-09-05 19:48 UTC, merged