Oleg homework lesson 6
AlexJavaGuru/java_1_tuesday_2021 pull request #22
Opened 2021-09-02 17:54 UTC by Olegs-github

2021-09-05 20:41 UTC, AlexJavaGuru requested changes
Надо поправить чуть-чуть

2021-09-05 20:41 UTC, AlexJavaGuru commented on src/main/java/student_oleg_kozlov/lesson_6/level_5/TicTacToe.java
> +    public boolean isDrawPosition(int[][] field) {
Может проще будет просто просканировать поле на предмет отсутствия значений -1? Это всего один цикл в 5 строк. Зачем проверять на победу сначала, если и в том и другом случае возвращаем false.

2021-09-05 20:41 UTC, AlexJavaGuru commented on src/main/java/student_oleg_kozlov/lesson_6/level_5/TicTacToe.java
> +    public boolean isWinPositionForDiagonals(int[][] field, int playerToCheck) {
Супер запутанный метод. Если бы я не знал, что тут делается, я бы очень не хотел разбираться в этом. 
Этот метод можно разбить на два, отдельных метода. В первом методе мы в одном цикле проходим по по массиву, используя field[i][i] - ведь нам надо посмотреть сверху в низ. Во втором методе, надо пройти снизу вверх. Для этого мы можем использовать field[i][field.lenght - i] - или наоборот, уже не помню. Попробуйте сделать этот метод более понятным.

2021-09-05 20:41 UTC, AlexJavaGuru commented on src/main/java/student_oleg_kozlov/lesson_6/level_5/TicTacToe.java
> +    public boolean isWinPositionForHorizontals(int[][] field, int playerToCheck) {
Вышел довольно сложный метод для простой задачи. Может попробуем упростить? Скажем, сканировать поле, на предмет числа field[i][j] != playerToCheck? Если хоть одно такое нашли, то можем сразу делать return false; а после цикла return true. Попробуйте упростить.

2021-09-05 20:41 UTC, AlexJavaGuru commented on src/main/java/student_oleg_kozlov/lesson_6/level_5/TicTacToe.java
> +    public boolean isWinPositionForVerticals(int[][] field, int playerToCheck) {
То же самое, что и верхний метод.

2021-09-05 20:41 UTC, AlexJavaGuru commented on src/main/java/student_oleg_kozlov/lesson_6/level_5/TicTacToe.java
> +    public Move checkComputerWinInOneTurn(int[][] field, int player) {
а в чем суть метода?

2021-09-08 11:27 UTC, Olegs-github commented on src/main/java/student_oleg_kozlov/lesson_6/level_5/TicTacToe.java
> +    public boolean isDrawPosition(int[][] field) {
Исправлено

2021-09-08 11:32 UTC, Olegs-github commented on src/main/java/student_oleg_kozlov/lesson_6/level_5/TicTacToe.java
> +    public Move checkComputerWinInOneTurn(int[][] field, int player) {
Идея была проверить, может ли компьютер выиграть следующим ходом и если да, то сделать этот ход за него. Во избежание клонирования поля, просто поочередно в цикле подставляем значение компьютера в пустые ячейки поля, проверяем выигрышная ли это позиция стандартным методом isWinPosition() и возвращаем в значение ячейки пустое значение. Если найден выигрышный ход, то он передается как ход компьютера на выполнение.

2021-09-08 11:38 UTC, Olegs-github commented on src/main/java/student_oleg_kozlov/lesson_6/level_5/TicTacToe.java
> +    public boolean isWinPositionForDiagonals(int[][] field, int playerToCheck) {
Исправлено

2021-09-08 12:42 UTC, Olegs-github commented on src/main/java/student_oleg_kozlov/lesson_6/level_5/TicTacToe.java
> +    public boolean isWinPositionForHorizontals(int[][] field, int playerToCheck) {
Исправлено. Не удалось избавиться от флага, но удалось уйти от счетчика и привязке к цифре 3.

2021-09-08 12:42 UTC, Olegs-github commented on src/main/java/student_oleg_kozlov/lesson_6/level_5/TicTacToe.java
> +    public boolean isWinPositionForVerticals(int[][] field, int playerToCheck) {
Исправлено. Не удалось избавиться от флага, но удалось уйти от счетчика и привязке к цифре 3.

2021-09-08 20:29 UTC, AlexJavaGuru approved these changes

2021-09-08 20:29 UTC, merged