Ruslan: fix Lesson_5 Task 1 - 43;
AlexJavaGuru/java_1_tuesday_2021 pull request #28
Opened 2021-09-10 11:07 UTC by RuslanPankratov

2021-09-13 19:42 UTC, AlexJavaGuru requested changes
Нужно поправить

2021-09-13 19:42 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_6/level_1/WhileDefinition2.java
> +        while (i <= 100)
А работает как нужно?

2021-09-13 19:42 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_6/level_3/ArrayService.java
> +                count = count + 1;
можно было просто count++

2021-09-13 19:42 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/RobotAI.java
> +    void checkOpponentsHorizontals(int[][] arr) {
Попробуйте сделать рефакторинг. Для начала, если этот метод отвечает за проверку победы по горизонтали, то он должен только это и проверять, а не проверять еще вертикаль. Сам алгоритм супер сложно написан.

2021-09-13 19:42 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/RobotAI.java
> +    void checkOpponentsVerticals(int[][] arr, boolean wasMove) {
То же самое тут.

2021-09-13 19:42 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/RobotAI.java
> +    void checkOpponentsDiagonals(int[][] arr, boolean wasMove) {
Нужен рефакторинг. Проверяйте в цикле, как мы показывали на лекции. Тут тоже надо проверять только диагонали.

2021-09-13 19:42 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/RobotAI.java
> +    void checkRobotsWinPositionHorizontally(int[][] arr, boolean wasMove) {
Чем отличается от обычной проверки? Почему мы не можем воспользоваться уже существующим методом проверки?

2021-09-13 19:42 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/RobotAI.java
> +    void checkRobotsWinPositionDiagonally(int[][] arr) {
Почему для робота отдельно?

2021-09-13 19:42 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/TicTacToe.java
> +            if (playerToCheck == field[i][0]) {
Может эти условия можно просто сделать через &&?

2021-09-13 19:42 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/TicTacToe.java
> +            if (field[0][i] == playerToCheck) {
Может эти условия можно просто сделать через &&?

2021-09-13 19:42 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/TicTacToe.java
> +    public boolean isWinPositionForDiagonals(int[][] field, int playerToCheck) {
Диагонали сделайте в цикле. Это просто.

2021-09-13 19:42 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/TicTacToe.java
> +    public boolean isDrawPosition(int[][] field) {
Drow можно проверить просто на отсутствие -1 во всех клетках. Тут можно упростить до двойного цикла.

2021-09-13 19:42 UTC, AlexJavaGuru commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/TicTacToeTest.java
> +        field[0][0] = 1;
Было бы более удобно задавать поле в {} 
Например:
= {{  1, 1, 1} ,
     {-1,-1-1},
     {-1,-1,-1}}

2021-09-14 09:51 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/TicTacToe.java
> +    public boolean isDrawPosition(int[][] field) {
в условии сказано, что не должно быть победной комбинации 

В классе TicTacToe реализуйте
метод для определения является ли данная позиция ничейной.

Подсказка: ничейной позиция является тогда, когда
позиция не победна ни для одного из игроков и нет ни
одной пустой клетки (клетки в которой стоит -1).

2021-09-14 11:32 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_6/level_3/ArrayService.java
> +                count = count + 1;
Done

2021-09-14 11:32 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/RobotAI.java
> +    void checkOpponentsHorizontals(int[][] arr) {
Done

2021-09-14 11:33 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/RobotAI.java
> +    void checkOpponentsVerticals(int[][] arr, boolean wasMove) {
Done

2021-09-14 11:33 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/RobotAI.java
> +    void checkOpponentsDiagonals(int[][] arr, boolean wasMove) {
Done

2021-09-14 11:33 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/TicTacToe.java
> +            if (playerToCheck == field[i][0]) {
Done

2021-09-14 11:33 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/TicTacToe.java
> +            if (field[0][i] == playerToCheck) {
Done

2021-09-14 11:33 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/TicTacToe.java
> +    public boolean isWinPositionForDiagonals(int[][] field, int playerToCheck) {
Done

2021-09-14 11:33 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/TicTacToe.java
> +    public boolean isDrawPosition(int[][] field) {
Done

2021-09-14 11:34 UTC, RuslanPankratov commented on src/main/java/student_ruslan_pankratov/lesson_6/level_5/TicTacToeTest.java
> +        field[0][0] = 1;
Done

2021-09-16 18:25 UTC, closed without merging