Em lesson 6
AlexJavaGuru/java_1_tuesday_2021 pull request #30
Opened 2021-09-12 19:09 UTC by Einarok

2021-09-16 19:01 UTC, AlexJavaGuru requested changes
Надо чуть-чуть поправить

2021-09-16 19:01 UTC, AlexJavaGuru commented on src/main/java/student_einars_marhilevics/lesson_6/level_5/TicTacToe.java
> +    boolean isWinPositionForDiagonals(int[][] field, int playerToCheck) {
Попробуйте переделать метод на красивый, универсальный. Можно разбить эту логику на два отдельных метода и решить задачу двумя одиночными циклами, как мы показывали на лекции.

2021-09-16 19:01 UTC, AlexJavaGuru commented on src/main/java/student_einars_marhilevics/lesson_6/level_5/TicTacToe.java
> +        if (isWinPositionForHorizontals(field, playerToCheck)) {
Можно просто перечислить все три метода через оператор || (OR).

2021-09-16 19:01 UTC, AlexJavaGuru commented on src/main/java/student_einars_marhilevics/lesson_6/level_5/TicTacToe.java
> +    boolean isDrawPosition(int[][] field) {
Проверяя drow, нам не надо проверять победу.

2021-09-18 19:11 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_6/level_5/TicTacToe.java
> +    boolean isWinPositionForDiagonals(int[][] field, int playerToCheck) {
fixed

2021-09-18 19:16 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_6/level_5/TicTacToe.java
> +        if (isWinPositionForHorizontals(field, playerToCheck)) {
fixed

2021-09-18 19:21 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_6/level_5/TicTacToe.java
> +    boolean isDrawPosition(int[][] field) {
fixed

2021-09-22 17:24 UTC, AlexJavaGuru approved these changes

2021-09-22 17:24 UTC, merged