Alberts Matrozis lesson6
AlexJavaGuru/java_1_tuesday_2021 pull request #34
Opened 2021-09-15 09:39 UTC by LurkErLV

2021-09-22 20:24 UTC, AlexJavaGuru requested changes

2021-09-22 20:24 UTC, AlexJavaGuru commented on src/main/java/student_alberts_matrozis/albertsUtils/Utils.java
> +    public static void fillArrayWithRandomNumbers(int[][] arr) {
Понимаю назначение класса, но не понимаю зачем тут эти два метода? Они вроде к тестам не относятся. Я бы разделил на два Util. TestHelper и ArrayUtil

2021-09-22 20:24 UTC, AlexJavaGuru commented on src/main/java/student_alberts_matrozis/lesson_6/level_3/ArrayService.java
> +                result = true;
Может будет лучше, если будем сразу возвращать true, если нашли искомое значение?

2021-09-22 20:24 UTC, AlexJavaGuru commented on src/main/java/student_alberts_matrozis/lesson_6/level_5/TicTacToe.java
> +        if (isWinPositionForVerticals(field, playerToCheck)) {
Может можно переделать условие при помощи операции ИЛИ?

2021-09-22 20:24 UTC, AlexJavaGuru commented on src/main/java/student_alberts_matrozis/lesson_6/level_5/TicTacToe.java
> +        if (field[0][0] == playerToCheck && field[1][1] == playerToCheck && field[2][2] == playerToCheck) {
Может можно переделать условие при помощи операции ИЛИ?

2021-09-22 20:24 UTC, AlexJavaGuru commented on src/main/java/student_alberts_matrozis/lesson_6/level_5/TicTacToe.java
> +        if (field[0][0] == playerToCheck && field[1][0] == playerToCheck && field[2][0] == playerToCheck) {
Может можно переделать условие при помощи операции ИЛИ?

2021-09-22 20:24 UTC, AlexJavaGuru commented on src/main/java/student_alberts_matrozis/lesson_6/level_5/TicTacToe.java
> +        if (field[0][0] == playerToCheck && field[0][1] == playerToCheck && field[0][2] == playerToCheck) {
Может можно переделать условие при помощи операции ИЛИ?

2021-09-22 20:24 UTC, AlexJavaGuru commented on src/main/java/student_alberts_matrozis/lesson_7/level_7/RepositoryUser.java
> +        return Arrays.copyOf(users, counter);
Зачем так сложно? Почему просто не вернуть массив из объектов?

2021-09-22 20:24 UTC, AlexJavaGuru commented on src/main/java/student_alberts_matrozis/lesson_7/level_7/RepositoryUser.java
> +    public void refactorUser(int id, String edit, String value) {
Лучше сделать метод типа updateUser и туда передавать новый объект и его паля засетать в существующий. Незачем делать switch при этой операции. Если у вас будет 10-15 полей у юзера, то вам не захочется поддерживать такой код.

2021-09-27 15:26 UTC, LurkErLV commented on src/main/java/student_alberts_matrozis/lesson_7/level_7/RepositoryUser.java
> +        return Arrays.copyOf(users, counter);
Эта строчка и выводит массив из объектов, только при помощи неё я возвращаю новый массив без значений null в нём, то есть из этого `[UserEntity{id=1, name='Misha', surname='Pituh', personalCode=58379}, UserEntity{id=6, name='Misha', surname='Smith', personalCode=1337228}, null, null, null]` я делаю это `[UserEntity{id=1, name='Misha', surname='Pituh', personalCode=58379}, UserEntity{id=6, name='Misha', surname='Smith', personalCode=1337228}]`

2021-09-27 20:17 UTC, AlexJavaGuru requested changes

2021-09-27 20:17 UTC, AlexJavaGuru commented on src/main/java/student_alberts_matrozis/lesson_7/level_7/RepositoryUser.java
> +    public void refactorUser(int id, UserEntity newUser) {
Если делаете много операций с объектом, то лучше просто его 1 раз найти, сохранить его в переменную а потом сетать в него новые значения. Сейчас вы делаете поиск 4 раза, хотя можно сделать его 1 раз.

2021-09-27 20:17 UTC, AlexJavaGuru commented on src/main/java/student_alberts_matrozis/lesson_7/level_7/RepositoryUser.java
> +        return Arrays.copyOf(users, counter);
Я понимаю ) Просто насколько это реально нужно? Ну можно оставить, т.к. с коллекциями будет проще...

2021-09-30 18:16 UTC, AlexJavaGuru approved these changes

2021-09-30 18:17 UTC, merged