Em lesson 7
AlexJavaGuru/java_1_tuesday_2021 pull request #36
Opened 2021-09-17 21:52 UTC by Einarok

Lesson 7

2021-09-26 18:28 UTC, AlexJavaGuru requested changes

2021-09-26 18:28 UTC, AlexJavaGuru commented on src/main/java/student_einars_marhilevics/lesson_7/level_7/UserEntityRepository.java
> +    public static void main(String[] args) {
Наверное не хотелось бы иметь main метод в репозитории. Лучше было бы вынести его в демо.

2021-09-26 18:28 UTC, AlexJavaGuru commented on src/main/java/student_einars_marhilevics/lesson_7/level_7/UserEntityRepository.java
> +    }
Crtl + Alt + L

2021-09-26 18:28 UTC, AlexJavaGuru commented on src/main/java/student_einars_marhilevics/lesson_7/level_7/UserEntityRepository.java
> +    public UserEntity[] getAllUsers() {
Ну если уже ввели коллекции чтобы облегчить себе жизнь, то уже до конца ) Возвращать тогда можно коллекцию

2021-09-26 18:28 UTC, AlexJavaGuru commented on src/main/java/student_einars_marhilevics/lesson_7/level_7/UserEntityRepository.java
> +    public void refactorUser(int id, String edit, String newName) {
В этот метод можно уже подавать готовый объект с новыми полями и посетать их в объект по ID.

2021-09-26 18:28 UTC, AlexJavaGuru commented on src/main/java/student_einars_marhilevics/lesson_7/level_7/WordService.java
> +    public String findMostFrequentWord(String text) {
Может можно разбить данную логику на 3 метода?

2021-09-29 13:18 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_7/level_7/UserEntityRepository.java
> +    public static void main(String[] args) {
fixed

2021-09-29 13:18 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_7/level_7/UserEntityRepository.java
> +    }
fixed

2021-09-29 13:28 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_7/level_7/UserEntityRepository.java
> +    public UserEntity[] getAllUsers() {
fixed

2021-09-29 13:54 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_7/level_7/WordService.java
> +    public String findMostFrequentWord(String text) {
fixed

2021-10-01 15:53 UTC, Einarok commented on src/main/java/student_einars_marhilevics/lesson_7/level_7/UserEntityRepository.java
> +    public void refactorUser(int id, String edit, String newName) {
fixed

2021-10-03 21:06 UTC, AlexJavaGuru approved these changes

2021-10-03 21:06 UTC, merged